version: '2.3'

services:
    sen2sr:
      image: deephdc/deep-oc-sen2sr
      # if 'docker-compose run' is used
      # do not forget '--service-ports'!
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    sen2sr-gpu:
      image: deephdc/deep-oc-sen2sr
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    sen2sr-rclone:
      extends:
        service: sen2sr
      volumes:
        - $HOME/.config/rclone:/srv/rclone
      environment:
        - RCLONE_CONFIG=/srv/rclone/rclone.conf
